M48
; DRILL file {KiCad 8.0.5} date 2024-11-12T22:59:26-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-12T22:59:26-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C7.500
%
G90
G05
T1
X200.715Y-278.445
X234.315Y-278.445
T2
X91.879Y-257.421
X237.879Y-257.421
M30
