M48
; DRILL file {KiCad (6.0.8-1)-1} date Friday, December 30, 2022 at 12:12:22 pm
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-12-30T12:12:22-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C7.500
%
G90
G05
T1
X200.715Y-278.445
X234.315Y-278.445
T2
X91.879Y-257.421
X237.879Y-257.421
T0
M30
